# Generated by Django 3.1.7 on 2021-03-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1),
        ),
    ]
