# Generated by Django 3.1.7 on 2021-03-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210316_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
    ]
